# Generated by Django 6.1.1 on 2026-10-02 13:32

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(max_length=50)),
                ('condition', models.CharField(choices=[('BASELINE', 'Baseline (Manual / Spreadsheet)'), ('FUNDSHARE', 'FundShare Prototype')], max_length=20)),
                ('task_index', models.IntegerField()),
                ('task_description', models.CharField(max_length=255)),
                ('completion_time_seconds', models.FloatField()),
                ('is_correct', models.BooleanField(default=True)),
                ('confidence_rating', models.IntegerField(default=5)),
                ('usability_score', models.FloatField(default=85.0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('CUSTOMER', 'Customer / Wallet Owner'), ('MEMBER', 'FamilyPass Member'), ('MERCHANT', 'Merchant'), ('ADMIN', 'Admin / Hackathon Evaluator')], default='CUSTOMER', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('avatar_url', models.CharField(blank=True, default='', max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('BUDGET_OVERRUN', 'Budget Overrun Risk'), ('SPENDING_TREND', 'Spending Trend'), ('REALLOCATION', 'Fund Reallocation Recommendation'), ('FAMILY_PASS_USAGE', 'FamilyPass Utilization'), ('SAVINGS_OPPORTUNITY', 'Savings Opportunity'), ('ANOMALY', 'Unusual Spending Flag')], max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('action_type', models.CharField(default='NONE', max_length=50)),
                ('action_payload', models.JSONField(blank=True, default=dict)),
                ('confidence', models.FloatField(default=0.88)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('used_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField()),
                ('allowed_action', models.CharField(choices=[('MERCHANT_PAYMENT', 'Merchant Payment Only'), ('ALL', 'All Actions'), ('GROCERY_MEDICINE', 'Grocery & Medicine Only')], default='MERCHANT_PAYMENT', max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('purpose_label', models.CharField(blank=True, default='Family Spending', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_family_passes', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_family_passes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('deadline', models.DateField()),
                ('status', models.CharField(default='IN_PROGRESS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('Grocery', 'Grocery'), ('Medicine', 'Medicine'), ('Treatment', 'Treatment'), ('Education', 'Education'), ('Electricity', 'Electricity'), ('Restaurant/Food', 'Restaurant / Food'), ('Transport', 'Transport'), ('Rent', 'Rent'), ('Shopping', 'Shopping'), ('Other', 'Other')], default='Other', max_length=50)),
                ('account_number', models.CharField(max_length=30, unique=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('FAMILY_PASS', 'FamilyPass Activity'), ('ANOMALY_ALERT', 'Spending Anomaly'), ('BUDGET_WARNING', 'Budget Overrun Warning'), ('TRANSACTION', 'Transaction Alert'), ('SYSTEM', 'System Alert')], default='TRANSACTION', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurposeFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Grocery', 'Grocery'), ('Medicine', 'Medicine'), ('Treatment', 'Treatment'), ('Education', 'Education'), ('Electricity', 'Electricity'), ('Restaurant/Food', 'Restaurant / Food'), ('Transport', 'Transport'), ('Rent', 'Rent'), ('Shopping', 'Shopping'), ('Other', 'Other')], max_length=50)),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('monthly_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('icon', models.CharField(default='wallet', max_length=50)),
                ('color', models.CharField(default='#10B981', max_length=30)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purpose_funds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FundTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_transfers', to=settings.AUTH_USER_MODEL)),
                ('destination_fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='fundshare_app.purposefund')),
                ('source_fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='fundshare_app.purposefund')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('allocated_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_spent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('predicted_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('potential_overrun', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('risk_level', models.CharField(choices=[('SAFE', 'Safe / On Track'), ('MODERATE', 'Moderate Risk'), ('HIGH_RISK', 'High Risk of Overrun')], default='SAFE', max_length=20)),
                ('explanation', models.TextField(blank=True)),
                ('model_version', models.CharField(default='linear_decay_forecaster_v1.0', max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='fundshare_app.purposefund')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('CASH_IN', 'Add Money / Cash In'), ('SEND_MONEY', 'Send Money'), ('RECEIVE_MONEY', 'Receive Money'), ('MERCHANT_PAYMENT', 'Merchant Payment'), ('MOBILE_RECHARGE', 'Mobile Recharge'), ('BILL_PAYMENT', 'Bill Payment'), ('CASH_OUT', 'Cash Out'), ('FUND_ALLOCATION', 'Purpose Fund Allocation'), ('FUND_TRANSFER', 'Inter-Fund Transfer')], max_length=30)),
                ('payment_source', models.CharField(choices=[('NORMAL_WALLET', 'Normal Wallet'), ('PURPOSE_FUND', 'Purpose Fund'), ('FAMILY_PASS', 'FamilyPass')], default='NORMAL_WALLET', max_length=30)),
                ('category', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed')], default='COMPLETED', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('reference', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('family_pass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='fundshare_app.familypass')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='fundshare_app.merchant')),
                ('purpose_fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='fundshare_app.purposefund')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FamilyPassTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining_limit_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('family_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='fundshare_app.familypass')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_pass_spendings', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_pass_detail', to='fundshare_app.transaction')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AnomalyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_anomaly', models.BooleanField(default=False)),
                ('anomaly_score', models.FloatField(default=0.0)),
                ('reason', models.TextField(blank=True)),
                ('features_summary', models.JSONField(blank=True, default=dict)),
                ('model_version', models.CharField(default='iso_forest_v1.0', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_analysis', to='fundshare_app.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['sender', 'timestamp'], name='fundshare_a_sender__3e0bf6_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type'], name='fundshare_a_transac_f6fab6_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['payment_source'], name='fundshare_a_payment_2ae9ab_idx'),
        ),
    ]
