# Generated by Django 5.2.5 on 2026-10-02 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundshare_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purposefund",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_purpose_funds",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("phone", models.CharField(max_length=30)),
                ("username", models.CharField(blank=True, default="", max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["owner", "phone"], name="fundshare_a_owner_i_28107f_idx"
                    ),
                    models.Index(
                        fields=["owner", "name"], name="fundshare_a_owner_i_5c3bdd_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "phone"), name="unique_owner_contact_phone"
                    )
                ],
            },
        ),
    ]
