# Generated by Django 5.2.5 on 2026-10-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundshare_app", "0004_update_transaction_item_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="familypass",
            name="allowed_categories",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="familypass",
            name="custom_purpose",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="familypass",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("Grocery", "Grocery"),
                    ("Education", "Education"),
                    ("Medical", "Medical"),
                    ("Shopping", "Shopping"),
                    ("Dining", "Dining"),
                    ("Transport", "Transport"),
                    ("Bills & Utilities", "Bills & Utilities"),
                    ("Emergency", "Emergency"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=50,
            ),
        ),
    ]
