# Generated by Django 5.2.18 on 2026-10-07 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundshare_app', '0006_backfill_allowed_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('fingerprint', models.CharField(max_length=64)),
                ('response', models.JSONField(default=dict)),
                ('response_status', models.PositiveSmallIntegerField(default=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='pin_failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='pin_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='transaction_pin',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddConstraint(
            model_name='familypass',
            constraint=models.CheckConstraint(condition=models.Q(('used_amount__gte', 0)), name='pass_used_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='familypass',
            constraint=models.CheckConstraint(condition=models.Q(('limit_amount__gt', 0)), name='pass_limit_positive'),
        ),
        migrations.AddConstraint(
            model_name='familypass',
            constraint=models.CheckConstraint(condition=models.Q(('used_amount__lte', models.F('limit_amount'))), name='pass_within_limit'),
        ),
        migrations.AddConstraint(
            model_name='merchant',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='merchant_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='purposefund',
            constraint=models.CheckConstraint(condition=models.Q(('current_balance__gte', 0)), name='fund_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='purposefund',
            constraint=models.CheckConstraint(condition=models.Q(('allocated_amount__gte', 0)), name='fund_allocation_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='purposefund',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_budget__gte', 0)), name='fund_budget_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='wallet_nonnegative'),
        ),
        migrations.AddField(
            model_name='financialrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='financialrequest',
            constraint=models.UniqueConstraint(fields=('user', 'key'), name='unique_user_financial_request'),
        ),
    ]
