# Generated by Django 5.2.18 on 2026-10-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundshare_app', '0009_canonical_phones_and_lockouts'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='familypass',
            index=models.Index(fields=['owner', 'status', 'expiry_date'], name='pass_owner_status_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='familypass',
            index=models.Index(fields=['member', 'status', 'expiry_date'], name='pass_member_status_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='familypasstransaction',
            index=models.Index(fields=['family_pass', '-timestamp'], name='pass_activity_time_idx'),
        ),
        migrations.AddIndex(
            model_name='purposefund',
            index=models.Index(fields=['owner', 'status'], name='fund_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='purposefund',
            index=models.Index(fields=['recipient', 'status'], name='fund_recipient_status_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['receiver', '-timestamp'], name='txn_receiver_time_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['family_pass', '-timestamp'], name='txn_pass_time_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['merchant', '-timestamp'], name='txn_merchant_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='familypasstransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='pass_activity_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='familypasstransaction',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_limit_after__gte', 0)), name='pass_activity_remaining_valid'),
        ),
        migrations.AddConstraint(
            model_name='fundtransfer',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='transfer_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='transaction_amount_positive'),
        ),
    ]
