# Generated by Django 5.2.18 on 2026-10-07 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundshare_app', '0010_postgresql_accounting_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalyresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='anomalyresult',
            index=models.Index(fields=['is_anomaly', '-created_at'], name='anomaly_flag_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='anomalyresult',
            constraint=models.CheckConstraint(condition=models.Q(('anomaly_score__gte', 0), ('anomaly_score__lte', 1)), name='anomaly_score_range'),
        ),
    ]
